spring:
  datasource:
    url: jdbc:h2:file:${user.home}\template\database
    driverClassName: org.h2.Driver
    name: template
    password: pass
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
server:
  port: 8080
  servlet:
    context-path: /template/api/v1/
