spring:
  datasource:
    url: jdbc:h2:file:${user.home}\template\database
    driverClassName: org.h2.Driver
    name: template
    password: pass
    username: sa
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 120000
      max-lifetime: 1800000
      connection-timeout: 30000
      leak-detection-threshold: 60000
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      connection.provider_disables_autocommit: true
    properties:
      hibernate:
        ddl-auto: update
        connection:
          handling_mode: DELAYED_ACQUISITION_AND_RELEASE_AFTER_TRANSACTION
        jdbc:
          batch_size: 50
        query:
          in_clause_parameter_padding: true
          fail_on_pagination_over_collection_fetch: true
          default_batch_fetch_size: 30
          optimizer:
            enabled: true
    transaction:
      default-timeout: 30
    database-platform: org.hibernate.dialect.H2Dialect
server:
  port: 8080
  servlet:
    context-path: /template/api/v1/
